#!/bin/bash

export EDITOR="vim"
export VISUAL="vim"
export PAGER="less"
export LANG="en_US.UTF-8"
export TERM="xterm-256color"

HISTSIZE=10000
HISTFILESIZE=20000
HISTCONTROL=ignoreboth:erasedups
shopt -s histappend

shopt -s checkwinsize
shopt -s cdspell
shopt -s cmdhist
shopt -s dotglob
shopt -s expand_aliases
shopt -s extglob
shopt -s globstar
shopt -s nocaseglob

PS1='\[\e[38;5;208;40;1m\][\[\e[92m\]\w\[\e[38;5;208m\]]\[\e[0m\]\n\[\e[93m\]\D{%Y-%m-%d}\[\e[0m\] \[\e[40;1m\]|\[\e[0m\] \[\e[38;5;196;40;1m\]\t\[\e[0m\] \[\e[40;1m\]|\[\e[0m\] \[\e[96;40;1;3m\]\u\[\e[93m\]@\[\e[38;5;201m\]\h\[\e[38;5;42;5m\]\$\[\e[0m\] '

alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'
alias ip='ip -color=auto'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

alias mkdir='mkdir -pv'
alias wget='wget -c'
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias top='top -d 1'

alias ports='netstat -tulpn'
alias listen='lsof -i -P | grep LISTEN'

alias update='dnf update'
alias install='dnf install'
alias remove='dnf remove'
alias search='dnf search'

alias hist='history'
alias c='clear'
alias sts='systemctl status'
alias stp='systemctl stop'
alias srt='systemctl start'


mkcd() { mkdir -p "$1" && cd "$1"; }
extract() {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xjf $1     ;;
            *.tar.gz)    tar xzf $1     ;;
            *.bz2)       bunzip2 $1     ;;
            *.rar)       unrar e $1     ;;
            *.gz)        gunzip $1      ;;
            *.tar)       tar xf $1      ;;
            *.tbz2)      tar xjf $1     ;;
            *.tgz)       tar xzf $1     ;;
            *.zip)       unzip $1       ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1        ;;
            *)           echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}


calc() {
    echo "scale=2; $*" | bc
}

command_separator() {
    echo -e "\033[38;5;226m$(printf '%.0s=' $(seq 1 $(tput cols)))\033[0m"
}

PROMPT_COMMAND="command_separator"

sysinfo() {
    echo -e "\033[0;36mHostname:\033[0m $(hostname)"
    echo -e "\033[0;36mKernel:\033[0m $(uname -r)"
    echo -e "\033[0;36mUptime:\033[0m $(uptime -p)"
    echo -e "\033[0;36mCPU:\033[0m $(lscpu | grep 'Model name' | cut -f 2 -d ":")"
    echo -e "\033[0;36mMemory:\033[0m $(free -h | awk '/^Mem:/ {print $3 "/" $2}')"
    echo -e "\033[0;36mDisk Usage:\033[0m $(df -h / | awk '/\// {print $(NF-1)}')"
}

welcome() {
    clear
    echo -e "\033[38;5;10m"
    echo "▗▄▄▄▖▗▖ ▗▖▗▄▄▖ ▗▄▄▖  ▗▄▖     ▗▖  ▗▖ ▗▄▖ ▗▄▄▄ ▗▄▄▄▖     ▗▄▖  ▗▄▄▖▗▄▄▄▖▗▄▄▄▖▗▖  ▗▖ ▗▄▖▗▄▄▄▖▗▄▄▄▖▗▄▄▄ "
    echo "  █  ▐▌ ▐▌▐▌ ▐▌▐▌ ▐▌▐▌ ▐▌    ▐▛▚▞▜▌▐▌ ▐▌▐▌  █▐▌       ▐▌ ▐▌▐▌     █    █  ▐▌  ▐▌▐▌ ▐▌ █  ▐▌   ▐▌  █"
    echo "  █  ▐▌ ▐▌▐▛▀▚▖▐▛▀▚▖▐▌ ▐▌    ▐▌  ▐▌▐▌ ▐▌▐▌  █▐▛▀▀▘    ▐▛▀▜▌▐▌     █    █  ▐▌  ▐▌▐▛▀▜▌ █  ▐▛▀▀▘▐▌  █"
    echo "  █  ▝▚▄▞▘▐▌ ▐▌▐▙▄▞▘▝▚▄▞▘    ▐▌  ▐▌▝▚▄▞▘▐▙▄▄▀▐▙▄▄▖    ▐▌ ▐▌▝▚▄▄▖  █  ▗▄█▄▖ ▝▚▞▘ ▐▌ ▐▌ █  ▐▙▄▄▖▐▙▄▄▀"
    echo -e "\033[0m"
    echo -e "\033[0;36mToday is $(date +'%A, %B %d, %Y')\033[0m"
    echo ""
    sysinfo
}

welcome

echo -e "\033[0;32mWelcome to the Matrix\033[0m"
